name: CI

on:
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2

    - uses: extractions/setup-crate@v1
      with:
        owner: sigoden
        name: argc
      
    - run: argc --argc-help | true
    - run: argc | true
    - run: argc build